### ISSUE TITLE
Demo images 추가

### ISSUE THREAD

**Issue by ymnseol** [gustn9609/kpmg_boosting#13]
## Additional Context
현재 데모 페이지 캡처 이미지가 깨져, README에 추가하기 어렵습니다.
가능하다면 추후 첨부가 필요할 것으로 보입니다.

**Comment by unknownburphy** [comment]
유민님 확인하였습니다. demo라면 PPT 프로토타입 페이지에 들어가있는 이미지 맞을까요? 괜찮으시다면 제가 해보겠습니다!

**Comment by ymnseol** [comment]
> 유민님 확인하였습니다. demo라면 PPT 프로토타입 페이지에 들어가있는 이미지 맞을까요? 괜찮으시다면 제가 해보겠습니다!

감사합니다! 해결 완료했습니다!
